### ISSUE TITLE
Might be a good idea to add -disable-host-node-id to startup command

### ISSUE THREAD

**Issue by jmcarbo** [sdelrio/consul#3]
Consul generates node ids from hostname and may conflict when you run two or more consul containers in the same host (might happen in swarm mode). Consul 8.1 has -disable-host-node-id flag to avoid this issue. Workarround in docker-compose until you change Dockerfile:

entrypoint: ["/usr/local/bin/containerpilot", "/usr/local/bin/docker-entrypoint.sh" ]
command:  ["agent", "-server", "-bootstrap-expect", "3", "-ui", "-client=0.0.0.0", "-retry-interval", "5s", "--log-level", "warn", "-disable-host-node-id" ]

**Comment by sdelrio** [comment]
Thank you very much @jmcarbo I will update as soon as I can.
