### ISSUE TITLE
Is there a way to enable https

### ISSUE THREAD

**Issue by chavezom** [sdelrio/consul#4]

**Comment by sdelrio** [comment]
Traefik + automatic Let's encrypt don't work for you?

**Comment by chavezom** [comment]
I have not used Traefik before, but I will try it. I tried to enable Consul ssl using CONSUL_LOCAL_CONFIG, but I see that the leader election scripts use http: https://github.com/sdelrio/consul/blob/master/bin/consul-manage#L47.  I need to secure consul because I will be storing Vault passwords.

**Comment by sdelrio** [comment]
So I think just a simple env var that sets https instead http will work for you

https://github.com/sdelrio/consul/blob/master/bin/consul-manage#L53

I will cose the issue but open it again if needed.
