### ISSUE TITLE
info

### ISSUE THREAD

**Issue by publicocean0** [sdelrio/consul#8]
how to mount a volume for saving kv data in a specific path?

**Comment by sdelrio** [comment]
https://github.com/sdelrio/consul/issues/5

But take in mind to make sure all containers deploy on separate nodes

**Comment by publicocean0** [comment]
ok thanks. First installation is up. Just a clarification i m new in the world docker & consul.  I read docker  swarm has a internal dns. I read consul is also a dns. In what cases it is better to use consul like dns in docker swarm ? Maybe when you realize internal networks?

**Comment by sdelrio** [comment]
Really it depends on your project. consul mainly usage is for the key/value storage part like etcd zookeper, but also it "can" be used for dns.

I never try consul as a replacement for docker swarm dns because I didn't need it. Don't know if it can even be replaced.
